#!/bin/bash

version_parts=(${DOCKER_TAG//./ })
short_version="$DOCKER_REPO":"${version_parts[0]}"."${version_parts[1]}"

latest="$DOCKER_REPO":latest

docker tag "$IMAGE_NAME" "$short_version"
docker push "$short_version"

docker tag "$IMAGE_NAME" "$latest"
docker push "$latest"
