name: ci

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "00 01 * * *"

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings

  test:
    name: test
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        build:
          - msrv
          - stable
          - beta
          - nightly
          - nightly-musl
          - nightly-32
          - nightly-arm
          - macos
          - win-msvc
          - win-gnu
        include:
          - build: msrv
            os: ubuntu-latest
            rust: 1.57.0
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: nightly-musl
            os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-musl
          - build: nightly-32
            os: ubuntu-latest
            rust: nightly
            target: i686-unknown-linux-gnu
          - build: nightly-arm
            os: ubuntu-latest
            rust: nightly
            target: arm-unknown-linux-gnueabihf
          - build: macos
            os: macos-latest
            rust: nightly
          - build: win-msvc
            os: windows-latest
            rust: nightly
          - build: win-gnu
            os: windows-latest
            rust: nightly-x86_64-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          target: ${{ matrix.target }}

      - name: Build warp-cors natively
        uses: actions-rs/cargo@v1
        if: matrix.target == ''
        with:
          command: build
          args: --verbose

      - name: Build warp-cors with cross
        uses: actions-rs/cargo@v1
        if: matrix.target != ''
        with:
          command: build
          use-cross: true
          args: --verbose --target ${{ matrix.target }}

      - name: Run tests natively
        uses: actions-rs/cargo@v1
        if: matrix.target == ''
        with:
          command: test

      - name: Run tests with cross
        uses: actions-rs/cargo@v1
        if: matrix.target != ''
        with:
          command: test
          use-cross: true
          args: --target ${{ matrix.target }}
